name: Sew Corellian
favicon: null
layout_spectrum: 0.4953
typography_spectrum: 0.73966
title: Costumes and Stitchery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#af957f'
    - '#7191a5'
    - '#89462d'
    - '#121111'
    - '#4e4a44'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
