name: sewcorellian
favicon: null
layout_spectrum: 0.73966
typography_spectrum: 0.49342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010103'
    - '#434e52'
    - '#7a8f92'
    - '#cb074e'
  brandStrength: 0.5
  lightness: 0.9879973798524588
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
